// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  apiKey: 'AIzaSyDRf9bnBv4qwsN2TRrR71Au8cSNFou16MU',
  envName: 'PROD',
};
